services:
  paddleocr-api:
    build: .
    container_name: paddleocr-api
    restart: unless-stopped
    ports:
      - "8866:8866"
    environment:
      OCR_LANG: fr
      PORT: "8866"
<<<<<<< HEAD
=======
      ROOT_PATH: /ocr-api
>>>>>>> main
    deploy:
      resources:
        limits:
          memory: 6G
