/** Permissions back-office admin (alignées mock jusqu'à endpoint dédié API). */
export const ADMIN_BACKOFFICE_PERMISSIONS: string[] = [
  "ops.dashboard.view",
  "ops.map.view",
  "ops.trips.view",
  "ops.trips.edit",
  "ops.dispatch.view",
  "ops.dispatch.assign",
  "network.franchises.view",
  "network.zones.view",
  "network.partners.view",
  "fleet.drivers.view",
  "fleet.drivers.status.bulk",
  "fleet.drivers.ban",
  "fleet.kyc.approve",
  "fleet.clients.view",
  "finance.transactions.view",
  "finance.withdrawals.approve",
  "finance.wallets.view",
  "settings.roles.manage",
  "settings.dispatchers.view",
  "settings.dispatchers.create",
  "settings.dispatchers.edit",
  "settings.dispatch_rules.view",
  "settings.dispatch_rules.edit",
  "settings.pricing.view",
];
